canal.id=1
canal.ip=
canal.port=11111
canal.metrics.pull.port=11112
canal.zkServers=
canal.serverMode=kafka
canal.destinations=memory-engine
canal.auto.scan=false

canal.mq.servers=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
canal.mq.flatMessage=true
